### ISSUE TITLE
support postcss7

### ISSUE THREAD

**Issue by xzysun** [vusion/css-sprite-loader#9]
安装了0.3.0版本的css-sprite-loader，build的时候有警告

Unknown error from PostCSS plugi n. Your current PostCSS version is 7.0.14, but css-sprite-parser uses 6.0.16. Perhaps this is the source of the error below.

同时build会失败
 ERROR in ./src/pages/User/UserPage/components/HistoryGamePage.less (./node_modules/css-loader!./node_modules/css-sprite-loader!./node_modules/postcss-loader/lib??postcss!./node_modules/less-loader/dist/cjs.js!./src/pages/User/UserPage/components/HistoryGamePage.less)
    Module build failed (from ./node_modules/css-sprite-loader/index.js):
    TypeError: Cannot read property 'options' of undefined
        at E:\avg-web\node_modules\css-sprite-loader\src\postcssPlugin.js:24:28
        at LazyResult.run (E:\avg-web\node_modules\base-css-image-loader\node_modules\postcss\lib\lazy-result.js:295:14)
        at LazyResult.asyncTick (E:\avg-web\node_modules\base-css-image-loader\node_modules\postcss\lib\lazy-result.js:208:26)
        at processing.Promise.then._this2.processed (E:\avg-web\node_modules\base-css-image-loader\node_modules\postcss\lib\lazy-result.js:250:14)
        at new Promise (<anonymous>)
        at LazyResult.async (E:\avg-web\node_modules\base-css-image-loader\node_modules\postcss\lib\lazy-result.js:246:23)
        at LazyResult.then (E:\avg-web\node_modules\base-css-image-loader\node_modules\postcss\lib\lazy-result.js:127:17)
        at Object.<anonymous> (E:\avg-web\node_modules\base-css-image-loader\src\createLoader.js:23:54)

我猜是因为引用的base-css-image-loader依赖了postcss7导致的依赖版本不符合？

**Comment by xzysun** [comment]
> 降 base-css-image-loader 的 postcss 的版本了，你重装一下试试还有没有问题。css-sprite-loader@0.3.1

更新了一下，可以正常的编译通过了。感谢~

**Comment by rainfore** [comment]
> > 降 base-css-image-loader 的 postcss 的版本了，你重装一下试试还有没有问题。css-sprite-loader@0.3.1
> 
> 更新了一下，可以正常的编译通过了。感谢~

好，如果好用的话，别忘记点个Star😄
